# Generated by Django 5.2.17 on 2026-08-29 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('baby_i_id', models.PositiveIntegerField(blank=True, null=True)),
                ('baby_ii_id', models.PositiveIntegerField(blank=True, null=True)),
                ('child_id', models.PositiveIntegerField(blank=True, null=True)),
                ('adult_id', models.PositiveIntegerField(blank=True, null=True)),
                ('perfect_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ultimate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('super_ultimate_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
